//
//  PokemonDetailsModels.swift
//  pokemon_app
//
//  Created by Mookmaleawja . on 7/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct PokemonDetails {
    // MARK: Use cases
    
    struct Details {
        struct Request {}
        struct Response: Decodable {
            var name: String
            var id: Int
            var experiencePoint: Int
            var height: Int
            var weight: Int
            var sprites: SpritesInfo?
            
            enum CodingKeys: String, CodingKey {
                case name
                case id
                case experiencePoint = "base_experience"
                case height
                case weight
                case sprites
            }
        }
        struct ViewModel {
        }
        struct SpritesInfo: Decodable {
            var frontImageUrl: String
            var backImageUrl: String
            var frontShineImageUrl: String
            var backShineImageUrl: String
            
            enum CodingKeys: String, CodingKey {
                case frontImageUrl = "front_default"
                case backImageUrl = "back_default"
                case frontShineImageUrl = "front_shiny"
                case backShineImageUrl = "back_shiny"
            }
        }
    }
}

