//
//  PokemonDetailsPresenter.swift
//  pokemon_app
//
//  Created by Mookmaleawja . on 7/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonDetailsPresentationLogic {
    func presentSetupView(info: PokemonDetails.Details.Response?)
}

class PokemonDetailsPresenter: PokemonDetailsPresentationLogic {
    var viewController: PokemonDetailsDisplayLogic?
    
    func presentSetupView(info: PokemonDetails.Details.Response?) {
        viewController?.displaySetupView(info: info)
    }
}
