//
//  PokemonDetailsInteractor.swift
//  pokemon_app
//
//  Created by Mookmaleawja . on 7/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol PokemonDetailsBusinessLogic {
    func fetchPokemonDetails()
}

protocol PokemonDetailsDataStore {
    var infomation: PokemonDetails.Details.Response? { get set }
}

class PokemonDetailsInteractor: PokemonDetailsBusinessLogic, PokemonDetailsDataStore {
    
    var presenter: PokemonDetailsPresentationLogic?
    var worker: PokemonDetailsWorker?
    
    var infomation: PokemonDetails.Details.Response?
    var name: String?
    
    func fetchPokemonDetails() {
        self.presenter?.presentSetupView(info: infomation)
    }
}
